apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: IconTest
  title: IconTest
  description: A template to test GitSync variables
  links:
    - url: www.google.com
      icon: wiz
spec:
  owner: c_neel.khamar@harness.io
  type: service
  parameters:
    - title: Deploy service
      required:
        - username
        - version
        - api_key
      properties:
        username:
          title: Username
          type: string
        api_key:
          title: API Key
          type: string
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        version:
          title: Version
          type: string
  steps:
    - id: trigger
      name: Run Deploy service
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/all/orgs/default/projects/Deepesh_CDE/pipelines/workflowtest/pipeline-studio?storeType=INLINE
        inputset:
          "username": ${{ parameters.username }}
          "pipeline.stages.deploy.variables.version": ${{ parameters.version }}
          "pipeline.stages.deploy.spec.execution.steps.ShellScript_1.spec.environmentVariables.scriptVar": ${{ parameters.username }}
        apikey: ${{ parameters.api_key }}
        token: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
